blank_issues_enabled: true
contact_links:
  - name: Ask a question
    url: https://github.com/sedlatschek/laravel-general-value-translations/discussions/new?category=q-a
    about: Ask the community for help
  - name: Request a feature
    url: https://github.com/sedlatschek/laravel-general-value-translations/discussions/new?category=ideas
    about: Share ideas for new features
  - name: Report a security issue
    url: https://github.com/sedlatschek/laravel-general-value-translations/security/policy
    about: Learn how to notify us for sensitive bugs
